# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Build network among a set of locations
#' 
#' @param locs A matrix of two columns containing xy-coordinates of locations.
#' @param weights A vector of expected number of edges for each location.
#' @param num_loc_candidate (Approximate) Number of nearest locations to establish edges with.
#' @param seed Random number seed.
#' @param min_x Smallest x value (helps with grid calculation)
#' @param min_x Smallest y value (helps with grid calculation)
#' @param steps Step size when doing neighbourhood searching
#' @return A matrix of two columns containing the edges: row id of location 1 and location 2.
#' @examples
#' locs <- matrix(c(-87.45, -87.0, -87.4, -87.5, -87.1, -87.1, 
#'                   24.8,   24.9,  25.1,  25.0,  24.85, 25.05), 6, 2)
#' build_network(locs, rep(2, 6), 3, 4326)
build_network <- function(locs, weights, num_loc_candidate, seed, min_x = -87.78555, min_y = 24.46990, steps = 2L) {
    .Call(`_abmgravity_build_network`, locs, weights, num_loc_candidate, seed, min_x, min_y, steps)
}

#' Build network among a set of locations with compliance score
#' 
#' @param locs A matrix of two columns containing xy-coordinates of locations.
#' @param weights A vector of expected number of edges for each location.
#' @param compliance A vector of compliance score
#' @param num_loc_candidate (Approximate) Number of nearest locations to establish edges with.
#' @param seed Random number seed.
#' @param min_x Smallest x value (helps with grid calculation)
#' @param min_x Smallest y value (helps with grid calculation)
#' @param steps Step size when doing neighbourhood searching
#' @return A matrix of two columns containing the edges: row id of location 1 and location 2.
build_network_wcomp <- function(locs, weights, compliance, num_loc_candidate, seed, min_x = -87.78555, min_y = 24.46990, steps = 2L) {
    .Call(`_abmgravity_build_network_wcomp`, locs, weights, compliance, num_loc_candidate, seed, min_x, min_y, steps)
}

#' Assigning ONE location to each point
#' 
#' @param pts A matrix of two columns containing xy-coordinates of points (e.g., person or house).
#' @param locs A matrix of two columns containing xy-coordinates of locations (e.g., schools or workplaces).
#' @param weights A vector of weights for each location (e.g., school or workplace size)
#' @param num_loc (Approximate) Number of nearest locations to consider for assignment (to each point).
#' @param seed Random number seed.
#' @param min_x Smallest x value (helps with grid calculation)
#' @param min_x Smallest y value (helps with grid calculation)
#' @param steps Step size when doing neighbourhood searching (affects efficiency)
#' @param use_capacity Logical indicating if the weights specified are to be interpreted as capacity; 
#' If TRUE, each time a location is allocated to a point, the weight/capacity is reduced by one. Default is FALSE.
#' @return A matrix of two columns containing specifying the assignment: row id of point and row id of location.
assign_by_gravity <- function(pts, locs, weights, num_loc, seed, min_x = -87.78555, min_y = 24.46990, steps = 2L, use_capacity = FALSE) {
    .Call(`_abmgravity_assign_by_gravity`, pts, locs, weights, num_loc, seed, min_x, min_y, steps, use_capacity)
}

#' Assigning one or more locations to each point
#' 
#' @param pts A matrix of two columns containing xy-coordinates of points (e.g., person or house).
#' @param locs A matrix of two columns containing xy-coordinates of locations (e.g., schools or workplaces).
#' @param weights A vector of weights for each location (e.g., school or workplace size)
#' @param num_loc_choose Number of locations to be assigned to each point.
#' @param num_loc_candidate (Approximate) Number of nearest locations to consider for assignment (to each point).
#' @param seed Random number seed.
#' @param min_x Smallest x value (helps with grid calculation)
#' @param min_x Smallest y value (helps with grid calculation)
#' @param steps Step size when doing neighbourhood searching (affects efficiency)
#' @param use_capacity Logical indicating if the weights specified are to be interpreted as capacity; 
#' If TRUE, each time a location is allocated to a point, the weight/capacity is reduced by one. Default is FALSE.
#' @param replace Logical indicating if a location can be assigned to a point multiple times.
#' @return A matrix of two columns containing specifying the assignment: row id of point and row id of location.
#' @examples
#' pts <- matrix(c(-87.45, -87.0, 24.85, 25.05), 2, 2)
#' locs <- matrix(c(-87.4, -87.5, -87.1, -87.1,
#'                   24.8,  24.9,  25.1,  25.0), 4, 2),
#' assign_by_gravity2(pts, locs, c(1, 1, 1, 1), 2, 3, 4328)
assign_by_gravity2 <- function(pts, locs, weights, num_loc_choose, num_loc_candidate, seed, min_x = -87.78555, min_y = 24.46990, steps = 2L, use_capacity = FALSE, replace = FALSE) {
    .Call(`_abmgravity_assign_by_gravity2`, pts, locs, weights, num_loc_choose, num_loc_candidate, seed, min_x, min_y, steps, use_capacity, replace)
}

