# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

build_network <- function(locs, weights, num_loc_candidate, seed, min_x = -87.78555, min_y = 24.46990, steps = 2L) {
    .Call(`_abmgravity_build_network`, locs, weights, num_loc_candidate, seed, min_x, min_y, steps)
}

assign_by_gravity <- function(pts, locs, weights, num_loc, seed, min_x = -87.78555, min_y = 24.46990, steps = 2L, use_capacity = FALSE) {
    .Call(`_abmgravity_assign_by_gravity`, pts, locs, weights, num_loc, seed, min_x, min_y, steps, use_capacity)
}

assign_by_gravity2 <- function(pts, locs, weights, num_loc_choose, num_loc_candidate, seed, min_x = -87.78555, min_y = 24.46990, steps = 2L, use_capacity = FALSE, replace = FALSE) {
    .Call(`_abmgravity_assign_by_gravity2`, pts, locs, weights, num_loc_choose, num_loc_candidate, seed, min_x, min_y, steps, use_capacity, replace)
}

